# Generated by Django 5.0.6 on 2024-05-29 11:16

import app.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_alter_adminuser_id_alter_job_id_alter_jobseeker_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='adminuser',
            name='id',
            field=models.CharField(default=app.models.generate_short_uuid, editable=False, max_length=8, primary_key=True, serialize=False, unique=True),
        ),
        migrations.AlterField(
            model_name='job',
            name='id',
            field=models.CharField(default=app.models.generate_short_uuid, editable=False, max_length=8, primary_key=True, serialize=False, unique=True),
        ),
        migrations.AlterField(
            model_name='jobseeker',
            name='id',
            field=models.CharField(default=app.models.generate_short_uuid, editable=False, max_length=8, primary_key=True, serialize=False, unique=True),
        ),
    ]
